## 1. 라이브러리 불러오기
Pytorch 실습을 위한 라이브러리 numpy, torch를 불러옵니다.

In [46]:
import numpy as np
import torch

## 2. Tensor 만들기

- torch.tensor()

In [45]:
torch.tensor(5)   # 0차원 텐서 → 스칼라

tensor(5)

In [46]:
torch.tensor([1, 2, 3, 4, 5])    # 1차원 텐서 → 벡터

tensor([1, 2, 3, 4, 5])

In [47]:
torch.tensor([[1], [2], [3], [4], [5]])   # 2차원 텐서 → 매트릭스
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

- list, set, numpy array 등에도 적용이 가능하다.

In [48]:
temp_list = [1, 2, 3, 4, 5]
torch.tensor(temp_list)

tensor([1, 2, 3, 4, 5])

In [49]:
temp_set = (1, 2, 3, 4, 5)
torch.tensor(temp_set)

tensor([1, 2, 3, 4, 5])

In [50]:
temp_np_array = np.array(temp_list)
torch.tensor(temp_np_array)

tensor([1, 2, 3, 4, 5])

In [51]:
torch.from_numpy(temp_np_array)

tensor([1, 2, 3, 4, 5])

- torch.ones()  
`torch.ones()`를 통해 만들게 되면 각 element가 1인 tensor를 만들어줌  
argment로는 tensor의 dimension을 입력

In [52]:
torch.ones(3)   # 1차원 텐서

tensor([1., 1., 1.])

In [53]:
torch.ones([3, 3])   # 2차원 텐서

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [54]:
torch.ones([3, 3, 3]) # 3차원 텐서

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

- torch.zeros()  
`torch.zeros()`를 통해 만들게 되면 각 element가 0인 tensor를 만들어줌    
argment로는 tensor의 dimension을 입력

In [55]:
torch.zeros(3)

tensor([0., 0., 0.])

In [56]:
torch.zeros([4, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [57]:
torch.zeros([3, 4, 4])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [58]:
torch.zeros([5, 3, 4, 4])

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],


- `torch.arange()`를 통해 주어진 범위 내의 정수를 순서대로 생성

In [59]:
torch.arange(1, 10)   # 10 이전까지

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
torch.arange(22, 10, -1)   # 10 이전까지 -1씩

tensor([22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [61]:
torch.arange(10, 22, 2)   # 22 전까지 2씩

tensor([10, 12, 14, 16, 18, 20])

-`torch.rand()`[0, 1]의 uniform dist에서 난수를 생성해서 tensor로 만들어줌

In [62]:
torch.rand(5)

tensor([0.2273, 0.8794, 0.1897, 0.8935, 0.9146])

In [63]:
torch.rand([3, 4, 5])

tensor([[[0.6737, 0.3843, 0.3143, 0.0402, 0.5812],
         [0.2231, 0.8884, 0.9587, 0.1562, 0.7619],
         [0.1924, 0.9641, 0.5009, 0.3172, 0.7799],
         [0.7401, 0.9243, 0.0152, 0.7182, 0.9502]],

        [[0.2842, 0.6153, 0.4420, 0.3958, 0.4843],
         [0.5193, 0.0982, 0.3453, 0.1006, 0.2304],
         [0.6074, 0.4937, 0.4825, 0.0820, 0.4184],
         [0.9258, 0.1279, 0.3099, 0.4751, 0.1970]],

        [[0.4681, 0.9547, 0.2008, 0.7247, 0.1027],
         [0.8245, 0.1674, 0.3609, 0.5722, 0.6900],
         [0.3005, 0.7414, 0.4602, 0.9773, 0.6292],
         [0.8618, 0.6924, 0.6197, 0.3227, 0.3255]]])

- `torch.xxx_like()`를 통해 기존의 텐서와 같은 모양의 원소가 지정해준 텐서를 만들어줌

In [64]:
a = torch.zeros([3, 4, 5])

In [65]:
torch.ones_like(a)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [66]:
torch.zeros_like(a)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [67]:
torch.rand_like(a)

tensor([[[0.0194, 0.0501, 0.3717, 0.0686, 0.6157],
         [0.4022, 0.5206, 0.6923, 0.2982, 0.4974],
         [0.9859, 0.4115, 0.7447, 0.8078, 0.5226],
         [0.2082, 0.1140, 0.3459, 0.5998, 0.6338]],

        [[0.5931, 0.8375, 0.4947, 0.9305, 0.7894],
         [0.0714, 0.2078, 0.5723, 0.0020, 0.1048],
         [0.3219, 0.9006, 0.3755, 0.4791, 0.1709],
         [0.5484, 0.5228, 0.7145, 0.1268, 0.1049]],

        [[0.3091, 0.0204, 0.5141, 0.0878, 0.8713],
         [0.6388, 0.2554, 0.6568, 0.4271, 0.6317],
         [0.3365, 0.3003, 0.2213, 0.7090, 0.2421],
         [0.0783, 0.5008, 0.4282, 0.0189, 0.1216]]])

## 3. Attribute : shape, dtype, device 
해당 텐서의 모양, 데이터 타입, 연결된 device(하드웨어)를 확인

- **`Tensor.shape`텐서의 사이즈 반환**    
가장 많이 사용하는 것들 중 하나

In [68]:
a= torch.tensor([1, 2, 3, 4, 5])
a.shape

torch.Size([5])

In [69]:
b = torch.ones([3, 4, 5])
b.shape

torch.Size([3, 4, 5])

- `Tensor.dtype` 텐서의 데이터 타입 반환
- 텐서 안에 다른 데이터 타입은 사용할 수 없음

In [70]:
a.dtype

torch.int64

- pytorch 자료형

In [5]:
# 자주 쓰는 것들 위주
float_tensor = torch.ones(1, dtype=torch.float)
double_tensor = torch.ones(1, dtype=torch.double)
int_tensor = torch.ones(1, dtype=torch.int)
long_tensor = torch.ones(1, dtype=torch.long)

bool_tensor = torch.ones(1, dtype=torch.bool)

- `Tensor.device`현재 해당 tensor가 어느 device에 있는지 확인하는 방법

In [6]:
a= torch.tensor([1, 2, 3, 4, 5])
a.device

device(type='cpu')

In [7]:
# 지금 GPU를 사용할 수 있는 환경인지를 확인
torch.cuda.is_available()

True

In [8]:
# 사용 가능 GPU 개수 체크
torch.cuda.device_count()

1

In [17]:
# 텐서를 gpu에 할당
a = torch.tensor([1., 2., 3.]).cuda()
b = torch.tensor([1., 2., 3.]).to("cuda")

In [21]:
a.device

device(type='cuda', index=0)

전에 **a.device**를 실행하였을 때 **cpu**로 할당되었지만 `.cuda()`를 선언하고 **gpu**로 할당되어진다.

## 4. Tensor Aggregation : element-wise 연산, min, max, mean

- `element-wise 연산`  
텐서의 같은 자리 원소들끼리 산술 연산

In [23]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [24]:
print(a.add(b))
print(a.sub(b))
print(a.mul(b))
print(a.div(b))

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


**add, sub, mul, div** 이용하여 계산하여도 똑같은 출력이 나온다.

- `inplace 연산`  
함수 뒤에 _를 붙이면 자기 자신의 값을 바꾸게 된다.  
연산 결과를 반환하면서 동시에 자기 자신의 데이터를 고친다.

In [26]:
print(a.add(b))
print(a)
print(a.add_(b))
print(a)

tensor([[ 6,  8],
        [10, 12]])
tensor([[1, 2],
        [3, 4]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])


보통 같으면 재선언 하는 방식으로 a = a.add(b)를 사용하겠지만  
인플레이스를 통해 선언없이 a.add_(b) 한방에 처리할 수 있다.

- `Tensor.min()` 가장 작은 값 반환, 차원을 넣어주면 해당 차원에서 가장 작은 값들과 그 값들의 위치를 함께 리턴
- `Tensor.max()` 가장 큰 값 반환, 차원을 넣어주면 해당 차원에서 가장 큰 값들과 그 값들의 위치를 함께 리턴

In [56]:
a = torch.tensor([[3, 1, 4], [2, 4, 5]])
print(a)
print()
print(a.shape)

tensor([[3, 1, 4],
        [2, 4, 5]])

torch.Size([2, 3])


In [54]:
print(a.min())
print()
print(a.min(dim=0))
print()
print(a.min(dim=1))

tensor(1)

torch.return_types.min(
values=tensor([2, 1, 4]),
indices=tensor([1, 0, 0]))

torch.return_types.min(
values=tensor([1, 2]),
indices=tensor([1, 0]))


In [55]:
print(a.max())
print()
print(a.max(dim=0))
print()
print(a.max(dim=1))

tensor(5)

torch.return_types.max(
values=tensor([3, 4, 5]),
indices=tensor([0, 1, 1]))

torch.return_types.max(
values=tensor([4, 5]),
indices=tensor([2, 2]))
